version: '3.8'

services:
  # Nginx webserver service
  nginx:
    image: nginx:1.18
    ports:
      - "8666:443"
    volumes:
      - ./src:/var/www/zadanieFINAL
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/certs:/etc/nginx/certs 
    depends_on:
      - php

  # PHP-FPM service
  php:
    build: ./.docker/php
    working_dir: /var/www/zadanieFINAL
    volumes:
      - ./src:/var/www/zadanieFINAL
    depends_on:
      - mysql

  # MySQL service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER:
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: webte_final_db
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/mysql.cnf
      - ./.database:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
  
  # phpMyAdmin interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8600:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata: